name: Lingo Translate

on:
  push:
    paths:
      - 'src/main/resources/static/locales/en.json'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npx lingo.dev@latest run
        env:
          LINGODOTDEV_API_KEY: ${{ secrets.api_o1kdbp728kkbkxt2e6u8tvft }}
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add src/main/resources/static/locales/*.json
          git commit -m "chore: auto-translate with Lingo.dev CLI" || exit 0
          git push